name: Build and Deploy APK

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Fazer upload do APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk

      - name: Checkout código
        uses: actions/checkout@v2

      - name: Baixar APK
        uses: actions/download-artifact@v2
        with:
          name: app-release
          path: app-release
          
      - name: Adicionar e commit APK
        run: |
          git add app-release
          git commit -m "Adicionar APK de release"
        
      - name: Release APK
     uses: ShowMeThe/github_action_release@v0.01
  with:
    # Github secret token to allow automated publishing of APK to release.
    GITHUB_TOKEN: # optional
