name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
    
 steps:
    check:
        image: runmymind/docker-android-sdk:latest
        when:
          branch: main
          event: [push, pull_request]
        commands:
          - ./gradlew build --stacktrace

    build:
        image: runmymind/docker-android-sdk:latest
        when:
          branch: main
          event: tag
        commands:
          - export RELEASE_STORE_FILE=$PWD/release-key.jks
          - echo $RELEASE_KEY | base64 -d > $RELEASE_STORE_FILE
          - ./gradlew -Psign assembleRelease --stacktrace
          - mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/savertuner.apk
        environment:
          - RELEASE_KEY_ALIAS=savertuner
        secrets: [ release_key, release_store_password, release_key_password ]
 # You may pin to the exact commit or the version.
  # uses: Shopify/upload-to-release@9942a4c936dab172f7101dcc7dc20528ea949102
  uses: Shopify/upload-to-release@v1.0.1
  with:
    # Artifact name
    name: savertunner
    # Path to the file to upload
    path: app/build/outputs/apk/release/app-release.apk
    # Content type for the file
    content-type: # optional, default is application/octet-stream
    # secrets.GITHUB_TOKEN
    repo-token: secrets.GITHUB_TOKEN
  
