name: Build and Deploy APK

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4.0.0

      - name: Configurar JDK 8
        uses: actions/setup-java@v3.12.0
        with:
          java-version: 1.8

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Fazer upload do APK
        uses: actions/upload-artifact@v3.1.3
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Baixar APK
        uses: actions/download-artifact@v2
        with:
          name: app-release
          path: app-release

      - name: Adicionar e commit APK
        run: |
          git add app-release
          git commit -m "Adicionar APK de release"
        
      - name: Fazer push do APK para o GitHub
        uses: ad-m/github-push-action@v0.6
        with:
          branch: main # Altere para a branch desejada
